/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.gasmeters.portlet.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Installed service. Represents a row in the &quot;GasMeters_Installed&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.gasmeters.portlet.model.impl.InstalledModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.gasmeters.portlet.model.impl.InstalledImpl}.
 * </p>
 *
 * @author George
 * @see Installed
 * @see com.gasmeters.portlet.model.impl.InstalledImpl
 * @see com.gasmeters.portlet.model.impl.InstalledModelImpl
 * @generated
 */
public interface InstalledModel extends BaseModel<Installed> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a installed model instance should use the {@link Installed} interface instead.
	 */

	/**
	 * Returns the primary key of this installed.
	 *
	 * @return the primary key of this installed
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this installed.
	 *
	 * @param primaryKey the primary key of this installed
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the serial nums of this installed.
	 *
	 * @return the serial nums of this installed
	 */
	public long getSerialNums();

	/**
	 * Sets the serial nums of this installed.
	 *
	 * @param serialNums the serial nums of this installed
	 */
	public void setSerialNums(long serialNums);

	/**
	 * Returns the date of this installed.
	 *
	 * @return the date of this installed
	 */
	public Date getDate();

	/**
	 * Sets the date of this installed.
	 *
	 * @param date the date of this installed
	 */
	public void setDate(Date date);

	/**
	 * Returns the curr ind of this installed.
	 *
	 * @return the curr ind of this installed
	 */
	public long getCurrInd();

	/**
	 * Sets the curr ind of this installed.
	 *
	 * @param currInd the curr ind of this installed
	 */
	public void setCurrInd(long currInd);

	/**
	 * Returns the group i d of this installed.
	 *
	 * @return the group i d of this installed
	 */
	public int getGroupID();

	/**
	 * Sets the group i d of this installed.
	 *
	 * @param groupID the group i d of this installed
	 */
	public void setGroupID(int groupID);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Installed installed);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Installed> toCacheModel();

	@Override
	public Installed toEscapedModel();

	@Override
	public Installed toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}