/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.gasmeters.portlet.model.impl;

import com.gasmeters.portlet.model.Installed;
import com.gasmeters.portlet.model.InstalledModel;
import com.gasmeters.portlet.model.InstalledSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Installed service. Represents a row in the &quot;GasMeters_Installed&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.gasmeters.portlet.model.InstalledModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link InstalledImpl}.
 * </p>
 *
 * @author George
 * @see InstalledImpl
 * @see com.gasmeters.portlet.model.Installed
 * @see com.gasmeters.portlet.model.InstalledModel
 * @generated
 */
@JSON(strict = true)
public class InstalledModelImpl extends BaseModelImpl<Installed>
	implements InstalledModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a installed model instance should use the {@link com.gasmeters.portlet.model.Installed} interface instead.
	 */
	public static final String TABLE_NAME = "GasMeters_Installed";
	public static final Object[][] TABLE_COLUMNS = {
			{ "serialNums", Types.BIGINT },
			{ "date_", Types.TIMESTAMP },
			{ "currInd", Types.BIGINT },
			{ "groupID", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table GasMeters_Installed (serialNums LONG not null primary key,date_ DATE null,currInd LONG,groupID INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table GasMeters_Installed";
	public static final String ORDER_BY_JPQL = " ORDER BY installed.date ASC";
	public static final String ORDER_BY_SQL = " ORDER BY GasMeters_Installed.date_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.gasmeters.portlet.model.Installed"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.gasmeters.portlet.model.Installed"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.gasmeters.portlet.model.Installed"),
			true);
	public static long DATE_COLUMN_BITMASK = 1L;
	public static long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Installed toModel(InstalledSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Installed model = new InstalledImpl();

		model.setSerialNums(soapModel.getSerialNums());
		model.setDate(soapModel.getDate());
		model.setCurrInd(soapModel.getCurrInd());
		model.setGroupID(soapModel.getGroupID());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Installed> toModels(InstalledSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Installed> models = new ArrayList<Installed>(soapModels.length);

		for (InstalledSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.gasmeters.portlet.model.Installed"));

	public InstalledModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _serialNums;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSerialNums(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _serialNums;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Installed.class;
	}

	@Override
	public String getModelClassName() {
		return Installed.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("serialNums", getSerialNums());
		attributes.put("date", getDate());
		attributes.put("currInd", getCurrInd());
		attributes.put("groupID", getGroupID());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long serialNums = (Long)attributes.get("serialNums");

		if (serialNums != null) {
			setSerialNums(serialNums);
		}

		Date date = (Date)attributes.get("date");

		if (date != null) {
			setDate(date);
		}

		Long currInd = (Long)attributes.get("currInd");

		if (currInd != null) {
			setCurrInd(currInd);
		}

		Integer groupID = (Integer)attributes.get("groupID");

		if (groupID != null) {
			setGroupID(groupID);
		}
	}

	@JSON
	@Override
	public long getSerialNums() {
		return _serialNums;
	}

	@Override
	public void setSerialNums(long serialNums) {
		_serialNums = serialNums;
	}

	@JSON
	@Override
	public Date getDate() {
		return _date;
	}

	@Override
	public void setDate(Date date) {
		_columnBitmask = -1L;

		if (_originalDate == null) {
			_originalDate = _date;
		}

		_date = date;
	}

	public Date getOriginalDate() {
		return _originalDate;
	}

	@JSON
	@Override
	public long getCurrInd() {
		return _currInd;
	}

	@Override
	public void setCurrInd(long currInd) {
		_currInd = currInd;
	}

	@JSON
	@Override
	public int getGroupID() {
		return _groupID;
	}

	@Override
	public void setGroupID(int groupID) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupID) {
			_setOriginalGroupID = true;

			_originalGroupID = _groupID;
		}

		_groupID = groupID;
	}

	public int getOriginalGroupID() {
		return _originalGroupID;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Installed.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Installed toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Installed)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		InstalledImpl installedImpl = new InstalledImpl();

		installedImpl.setSerialNums(getSerialNums());
		installedImpl.setDate(getDate());
		installedImpl.setCurrInd(getCurrInd());
		installedImpl.setGroupID(getGroupID());

		installedImpl.resetOriginalValues();

		return installedImpl;
	}

	@Override
	public int compareTo(Installed installed) {
		int value = 0;

		value = DateUtil.compareTo(getDate(), installed.getDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Installed)) {
			return false;
		}

		Installed installed = (Installed)obj;

		long primaryKey = installed.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		InstalledModelImpl installedModelImpl = this;

		installedModelImpl._originalDate = installedModelImpl._date;

		installedModelImpl._originalGroupID = installedModelImpl._groupID;

		installedModelImpl._setOriginalGroupID = false;

		installedModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Installed> toCacheModel() {
		InstalledCacheModel installedCacheModel = new InstalledCacheModel();

		installedCacheModel.serialNums = getSerialNums();

		Date date = getDate();

		if (date != null) {
			installedCacheModel.date = date.getTime();
		}
		else {
			installedCacheModel.date = Long.MIN_VALUE;
		}

		installedCacheModel.currInd = getCurrInd();

		installedCacheModel.groupID = getGroupID();

		return installedCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{serialNums=");
		sb.append(getSerialNums());
		sb.append(", date=");
		sb.append(getDate());
		sb.append(", currInd=");
		sb.append(getCurrInd());
		sb.append(", groupID=");
		sb.append(getGroupID());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.gasmeters.portlet.model.Installed");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>serialNums</column-name><column-value><![CDATA[");
		sb.append(getSerialNums());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>date</column-name><column-value><![CDATA[");
		sb.append(getDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>currInd</column-name><column-value><![CDATA[");
		sb.append(getCurrInd());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupID</column-name><column-value><![CDATA[");
		sb.append(getGroupID());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Installed.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Installed.class
		};
	private long _serialNums;
	private Date _date;
	private Date _originalDate;
	private long _currInd;
	private int _groupID;
	private int _originalGroupID;
	private boolean _setOriginalGroupID;
	private long _columnBitmask;
	private Installed _escapedModel;
}